general {
    # ロックが必要な時に呼ばれるコマンド
    lock_cmd = pidof hyprlock || hyprlock
    # スリープ（サスペンド）に入る前にロックをかける
    before_sleep_cmd = loginctl lock-session
}

# first rule
listener {
    timeout = 300 # unit sec
    on-timeout = loginctl lock-session
    #on-timeout = notify-send "You are idle!" # command to run when timeout has passed.
    #on-resume = notify-send "Welcome back!"  # command to run when activity is detected after timeout has fired.
}

# second rule
listener {
    timeout = 600 # unit sec
    on-timeout = niri msg action power-off-monitors
    on-resume  = niri msg action power-on-monitors
}
